[package]
name = "client"
version = "0.1.0"
authors = ["jrieck <jack.rieck@sendgrid.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
